/*
antennaApp is a package for creating and curating blog, link blogs and social websites
Copyright (C) 2025 R. S. Doiel

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
*/
package antennaApp

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// DefaultCSS is a comprehensive starter stylesheet for Antenna-generated pages.
// It includes CSS custom properties, dark-mode support, skip-link accessibility
// rules, and styles for all HTML structures the generator produces.
const DefaultCSS = `/* Antenna App — Default CSS
 * Generated by: antenna css
 *
 * Customize by editing this file or overriding the CSS custom properties.
 *
 * Sections:
 *   1. Custom properties (CSS variables)
 *   2. Dark-mode overrides
 *   3. Reset and base
 *   4. Accessibility — skip navigation link (WCAG 2.4.1)
 *   5. Layout
 *   6. Navigation
 *   7. Articles — shared base
 *   8. Feed item cards (aggregate collection pages)
 *   9. Standalone post / page articles
 *  10. Typography — headings, code, blockquotes, tables
 *  11. Site footer
 *  12. Images and media
 */

/* ------------------------------------------------------------------ */
/* 1. Custom properties                                                 */
/* ------------------------------------------------------------------ */
:root {
  /* Colors */
  --color-text:              #222222;
  --color-bg:                #ffffff;
  --color-link:              #005a9c;
  --color-link-hover:        #003366;
  --color-border:            #cccccc;

  /* Code blocks */
  --color-code-bg:           #f5f5f5;
  --color-code-border:       #dddddd;

  /* Blockquote */
  --color-blockquote-text:   #555555;
  --color-blockquote-border: #bbbbbb;

  /* Navigation */
  --color-nav-bg:            #333333;
  --color-nav-text:          #ffffff;
  --color-nav-hover:         #ffcc00;

  /* Site footer */
  --color-footer-bg:         #222222;
  --color-footer-text:       #cccccc;
  --color-footer-link:       #ffcc00;

  /* Feed item cards */
  --color-card-border:       #e0e0e0;
  --color-card-meta:         #777777;

  /* Typography */
  --font-body:   system-ui, -apple-system, sans-serif;
  --font-mono:   ui-monospace, "Cascadia Code", "Source Code Pro", monospace;
  --font-size:   1rem;
  --line-height: 1.65;

  /* Layout */
  --max-width:    72rem;
  --content-pad:  1rem;
}

/* ------------------------------------------------------------------ */
/* 2. Dark-mode overrides                                               */
/* ------------------------------------------------------------------ */
@media (prefers-color-scheme: dark) {
  :root {
    --color-text:              #e0e0e0;
    --color-bg:                #1a1a1a;
    --color-link:              #6ab0f5;
    --color-link-hover:        #9ecfff;
    --color-border:            #444444;
    --color-code-bg:           #2a2a2a;
    --color-code-border:       #444444;
    --color-blockquote-text:   #aaaaaa;
    --color-blockquote-border: #555555;
    --color-nav-bg:            #111111;
    --color-footer-bg:         #111111;
    --color-footer-text:       #aaaaaa;
    --color-card-border:       #333333;
    --color-card-meta:         #888888;
  }
}

/* ------------------------------------------------------------------ */
/* 3. Reset and base                                                    */
/* ------------------------------------------------------------------ */
*, *::before, *::after {
  box-sizing: border-box;
}

html {
  font-size: var(--font-size);
  line-height: var(--line-height);
  scroll-behavior: smooth;
}

body {
  font-family: var(--font-body);
  color: var(--color-text);
  background-color: var(--color-bg);
  margin: 0;
  padding: 0;
  min-height: 100vh;
}

/* ------------------------------------------------------------------ */
/* 4. Accessibility — skip navigation link (WCAG 2.4.1)                */
/*    Hidden off-screen until focused by keyboard users.               */
/* ------------------------------------------------------------------ */
.skip-link {
  position: absolute;
  top: -999px;
  left: -999px;
  padding: 0.5rem 1rem;
  background: var(--color-nav-bg);
  color: var(--color-nav-text);
  text-decoration: none;
  z-index: 9999;
}

.skip-link:focus {
  position: static;
  top: auto;
  left: auto;
  display: block;
}

/* ------------------------------------------------------------------ */
/* 5. Layout                                                            */
/* ------------------------------------------------------------------ */
main {
  max-width: var(--max-width);
  margin: 0 auto;
  padding: var(--content-pad);
}

/* ------------------------------------------------------------------ */
/* 6. Navigation                                                        */
/* ------------------------------------------------------------------ */
nav[aria-label="Site navigation"] {
  background-color: var(--color-nav-bg);
  padding: 0.5rem var(--content-pad);
}

nav[aria-label="Site navigation"] ul {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-wrap: wrap;
  gap: 0.25rem 1rem;
  align-items: center;
}

nav[aria-label="Site navigation"] a {
  color: var(--color-nav-text);
  text-decoration: none;
}

nav[aria-label="Site navigation"] a:hover,
nav[aria-label="Site navigation"] a:focus {
  color: var(--color-nav-hover);
  text-decoration: underline;
}

/* ------------------------------------------------------------------ */
/* 7. Articles — shared base                                            */
/* ------------------------------------------------------------------ */
article {
  border-bottom: 1px solid var(--color-card-border);
  padding: 1rem 0;
}

article:last-child {
  border-bottom: none;
}

a {
  color: var(--color-link);
}

a:hover,
a:focus {
  color: var(--color-link-hover);
}

/* ------------------------------------------------------------------ */
/* 8. Feed item cards (aggregate / collection pages)                   */
/*    Each harvested item: <article> > <h2>, <p><time>, <p>, <footer>  */
/* ------------------------------------------------------------------ */
article h2 {
  margin: 0 0 0.25rem 0;
  font-size: 1.15rem;
  font-weight: 600;
}

article h2 a {
  color: var(--color-link);
  text-decoration: none;
}

article h2 a:hover,
article h2 a:focus {
  color: var(--color-link-hover);
  text-decoration: underline;
}

article time {
  font-size: 0.875rem;
  color: var(--color-card-meta);
}

/* Source link at the bottom of each feed item card */
article footer {
  margin-top: 0.5rem;
  font-size: 0.8rem;
  color: var(--color-card-meta);
}

article footer a {
  color: var(--color-card-meta);
  word-break: break-all;
}

/* ------------------------------------------------------------------ */
/* 9. Standalone post / page articles                                  */
/*    A single <article> inside <main> with an <h1>.                   */
/* ------------------------------------------------------------------ */
article h1 {
  margin: 0 0 0.5rem 0;
  line-height: 1.2;
}

/* ------------------------------------------------------------------ */
/* 10. Typography — headings, code, blockquotes, tables                */
/* ------------------------------------------------------------------ */
h1, h2, h3, h4, h5, h6 {
  line-height: 1.25;
  margin-top: 1.75rem;
  margin-bottom: 0.5rem;
}

p {
  margin: 0.75rem 0;
}

pre {
  background: var(--color-code-bg);
  border: 1px solid var(--color-code-border);
  border-radius: 4px;
  padding: 1rem;
  overflow-x: auto;
  font-family: var(--font-mono);
  font-size: 0.9rem;
  line-height: 1.5;
}

code {
  font-family: var(--font-mono);
  font-size: 0.9em;
  background: var(--color-code-bg);
  border: 1px solid var(--color-code-border);
  border-radius: 3px;
  padding: 0.1em 0.35em;
}

pre code {
  border: none;
  background: none;
  padding: 0;
  font-size: inherit;
}

blockquote {
  margin: 1rem 0;
  padding: 0.5rem 1rem;
  border-left: 4px solid var(--color-blockquote-border);
  color: var(--color-blockquote-text);
}

table {
  border-collapse: collapse;
  width: 100%;
  margin: 1rem 0;
  font-size: 0.95rem;
}

th, td {
  border: 1px solid var(--color-border);
  padding: 0.5rem 0.75rem;
  text-align: left;
  vertical-align: top;
}

th {
  background-color: var(--color-code-bg);
  font-weight: bold;
}

tr:nth-child(even) td {
  background-color: var(--color-code-bg);
}

/* ------------------------------------------------------------------ */
/* 11. Site footer                                                      */
/* ------------------------------------------------------------------ */
body > footer {
  background-color: var(--color-footer-bg);
  color: var(--color-footer-text);
  padding: 1rem var(--content-pad);
  margin-top: 2rem;
  font-size: 0.875rem;
}

body > footer a {
  color: var(--color-footer-link);
}

body > footer a:hover,
body > footer a:focus {
  text-decoration: underline;
}

/* ------------------------------------------------------------------ */
/* 12. Images and media                                                 */
/* ------------------------------------------------------------------ */
img, video {
  max-width: 100%;
  height: auto;
}

svg {
  vertical-align: middle;
}
`

// patchGeneratorYAML adds a stylesheet link entry to a generator YAML file.
// Returns (true, "", nil) when the file was modified, (false, message, nil)
// when no change was made (already configured or instructions given), and
// (false, "", err) on I/O failure.
func patchGeneratorYAML(pageYamlPath string, cssHref string) (patched bool, msg string, err error) {
	src, err := os.ReadFile(pageYamlPath)
	if err != nil {
		return false, "", err
	}
	content := string(src)

	// Already configured — nothing to do
	if strings.Contains(content, cssHref) {
		return false, fmt.Sprintf("%s already references %s — no change made", pageYamlPath, cssHref), nil
	}

	// Has an existing link: section — don't risk reformatting it; instruct instead
	if strings.Contains(content, "\nlink:") || strings.HasPrefix(content, "link:") {
		return false, fmt.Sprintf("add the following entry to the link: section in %s:\n  - rel: stylesheet\n    type: text/css\n    href: %s", pageYamlPath, cssHref), nil
	}

	// No link: section yet — safe to append the block
	entry := fmt.Sprintf("\nlink:\n  - rel: stylesheet\n    type: text/css\n    href: %s\n", cssHref)
	f, err := os.OpenFile(pageYamlPath, os.O_APPEND|os.O_WRONLY, 0664)
	if err != nil {
		return false, "", err
	}
	defer f.Close()
	if _, err := f.WriteString(entry); err != nil {
		return false, "", err
	}
	return true, "", nil
}

/** GenerateCSS writes a sensible default CSS file and patches the generator
 * YAML to reference it.
 *
 * Parameters:
 *   out     (io.Writer) — progress messages
 *   cssPath (string)    — relative path within Htdocs (e.g. "css/site.css")
 *
 * Returns:
 *   error — non-nil on I/O failure
 *
 * Example:
 *   err := cfg.GenerateCSS(os.Stdout, "css/site.css")
 */
func (cfg *AppConfig) GenerateCSS(out io.Writer, cssPath string) error {
	// Resolve absolute file path within htdocs
	absCSS := cssPath
	if cfg.Htdocs != "" {
		absCSS = filepath.Join(cfg.Htdocs, cssPath)
	}

	// Create directory tree if needed
	cssDir := filepath.Dir(absCSS)
	if _, err := os.Stat(cssDir); err != nil {
		if err := os.MkdirAll(cssDir, 0775); err != nil {
			return fmt.Errorf("cannot create %s: %s", cssDir, err)
		}
	}

	// Backup existing file before overwriting
	if _, err := os.Stat(absCSS); err == nil {
		bakPath := absCSS + ".bak"
		if err := os.Rename(absCSS, bakPath); err != nil {
			return fmt.Errorf("cannot backup %s: %s", absCSS, err)
		}
		fmt.Fprintf(out, "backed up %s → %s\n", absCSS, bakPath)
	}

	// Write the default CSS
	if err := os.WriteFile(absCSS, []byte(DefaultCSS), 0664); err != nil {
		return fmt.Errorf("cannot write %s: %s", absCSS, err)
	}
	fmt.Fprintf(out, "wrote %s\n", absCSS)

	// Patch the generator YAML to reference the new CSS
	if cfg.Generator != "" {
		// Derive the URL href: absolute path from web root
		href := "/" + strings.TrimLeft(filepath.ToSlash(cssPath), "/")
		patched, msg, err := patchGeneratorYAML(cfg.Generator, href)
		if err != nil {
			fmt.Fprintf(out, "warning: could not patch %s: %s\n", cfg.Generator, err)
			fmt.Fprintf(out, "Manually add this to %s:\n\nlink:\n  - rel: stylesheet\n    type: text/css\n    href: %s\n\n", cfg.Generator, href)
		} else if patched {
			fmt.Fprintf(out, "updated %s with stylesheet link → %s\n", cfg.Generator, href)
		} else {
			fmt.Fprintf(out, "%s\n", msg)
		}
	}
	return nil
}

/** GenerateCSS implements the "css" action. Writes a default CSS file to the
 * htdocs tree and patches the configured generator YAML.
 *
 * Parameters:
 *   out     (io.Writer) — progress messages
 *   cfgName (string)    — path to antenna.yaml
 *   args    ([]string)  — optional: [css-output-path] (default: css/site.css)
 *
 * Returns:
 *   error — non-nil on configuration or I/O failure
 *
 * Example:
 *   err := app.GenerateCSS(os.Stdout, "antenna.yaml", nil)
 */
func (app *AntennaApp) GenerateCSS(out io.Writer, cfgName string, args []string) error {
	cfg := &AppConfig{}
	if err := cfg.LoadConfig(cfgName); err != nil {
		return err
	}
	cssPath := "css/site.css"
	if len(args) > 0 {
		cssPath = strings.TrimSpace(args[0])
	}
	return cfg.GenerateCSS(out, cssPath)
}
